-- Add seven recent AI research and technical blogs to Supabase public.blogs.
begin;

insert into public.blogs (
  id, title, excerpt, author, author_avatar, category, tags, read_time,
  publish_date, source_name, url, cover_image, cover_alt, cover_fit, status, featured
)
values
  (
    'typesafe-system-one-models-jev',
    'Introducing System One Models & Jev',
    'TypeSafe AI introduces Jev, a System One Model that maps unstructured state directly to typed probabilistic decisions, using parallel sampling and reinforcement learning for calibrated, low-latency software automation.',
    'Diogo Almeida',
    'https://www.google.com/s2/favicons?domain=typesafe.ai&sz=128',
    'Foundation Model',
    array['System One Models', 'Structured Output', 'Calibration', 'Low-Latency Inference', 'RLCD'],
    '10 min read',
    '2026-09-15',
    'TypeSafe AI',
    'https://typesafe.ai/blog/introducing-system-one-models-and-jev',
    'assets/img/covers/real/jev.png',
    'Introducing System One Models and Jev article cover',
    'cover',
    'published',
    false
  ),
  (
    'axi-embodied-talk-5-post-astra',
    '具身十日谈：飞越奇点，后 ASTRA 时代的具身智能',
    'Axi examines embodied AI after ASTRA, arguing that general-purpose models can strengthen planning and tool use but do not eliminate the need for robot data, specialized VLA models, distillation, and low-latency edge deployment.',
    '阿汐',
    'https://www.google.com/s2/favicons?domain=axi404.top&sz=128',
    'Frontier',
    array['Embodied AI', 'Vision-Language-Action', 'Robot Learning', 'Model Distillation', 'Edge Inference'],
    '14 min read',
    '2026-09-14',
    'Axi''s Blog',
    'https://axi404.top/blog/embodied-talk-5',
    'assets/img/covers/real/embodied_talk_5.png',
    'Post-ASTRA embodied intelligence article cover',
    'cover',
    'published',
    false
  ),
  (
    'huggingface-reef-self-improving-agents',
    'Your Inference Server Is Secretly a Learner: Reef Infrastructure for Continual Self-Improving Agents',
    'Reef turns production inference into a continual learning loop that records experience, evolves model weights and agent harnesses, evaluates candidate updates, and safely deploys versioned artifacts without interrupting service.',
    'Ao Qu et al.',
    'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
    'AI Agents',
    array['Continual Learning', 'Self-Improving Agents', 'Inference Serving', 'Agent Infrastructure', 'Online Learning'],
    '12 min read',
    '2026-09-15',
    'Hugging Face',
    'https://huggingface.co/blog/quao627/your-inference-server-is-secretly-a-learner-reef',
    'assets/img/covers/real/your-inference-server-is-secretly-a-learner-reef.png',
    'Reef infrastructure for continual self-improving agents article cover',
    'cover',
    'published',
    false
  ),
  (
    'jasper-lu-training-search-agents-grpo',
    'Training Search Agents with GRPO',
    'Jasper Lu presents a reproducible workflow for training SEC-filing search agents with GRPO, studying how reward design, learning rate, batch size, scale, and reward shaping change multi-step retrieval behavior.',
    'Jasper Lu',
    'https://www.google.com/s2/favicons?domain=jasperlu.com&sz=128',
    'AI Agents',
    array['GRPO', 'Search Agents', 'Reinforcement Learning', 'Information Retrieval', 'Reward Shaping'],
    '12 min read',
    '2026-08-24',
    'Jasper Lu',
    'https://jasperlu.com/blog/training-search-agents-grpo/',
    'assets/img/covers/real/agents_grpo.png',
    'Training search agents with GRPO article cover',
    'cover',
    'published',
    false
  ),
  (
    'anthropic-claude-biomolecular-modeling',
    'How Claude Is Uplifting Biomolecular Modeling',
    'Anthropic reports that Claude optimized more than 30 open-source biology models, developed faster pairwise GPU kernels, enabled lower-memory structure prediction, and reduced the compute needed for protein-design experiments.',
    'Anthropic',
    'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
    'Efficient AI',
    array['Biomolecular Modeling', 'GPU Optimization', 'Protein Design', 'Scientific Computing', 'AI for Science'],
    '10 min read',
    '2026-09-17',
    'Anthropic',
    'https://www.anthropic.com/research/claude-uplifts-biomolecular-modeling',
    'assets/img/covers/real/claude_uplifts_biomolecular_modeling.png',
    'Claude uplifting biomolecular modeling article cover',
    'cover',
    'published',
    false
  ),
  (
    'grant-sanderson-math-more-than-proof',
    'If Math Is More Than Proof, We Need to Better Celebrate the Rest of It',
    'Grant Sanderson argues that mathematical progress should reward motivated explanation alongside proof, especially as AI changes proof production, and proposes open exposition problems and stronger academic recognition for explanatory work.',
    'Grant Sanderson',
    'https://www.google.com/s2/favicons?domain=terrytao.wordpress.com&sz=128',
    'Research Craft',
    array['Mathematical Exposition', 'AI-Assisted Mathematics', 'Human Understanding', 'Research Culture', 'Open Exposition Problems'],
    '12 min read',
    '2026-09-18',
    'Terence Tao''s What''s New',
    'https://terrytao.wordpress.com/2026/09/18/if-math-is-more-than-proof-we-need-to-better-celebrate-the-rest-of-it/',
    'assets/img/covers/real/f-math-is-more-than-proof-we-need-to-better-celebrate-the-rest-of-it.png',
    'If math is more than proof article cover',
    'cover',
    'published',
    false
  ),
  (
    'laurentiu-raducu-how-i-use-llms-to-learn',
    'How I Use LLMs to Learn Complex Topics',
    'Laurentiu Raducu describes a workflow for using coding agents to research, verify, visualize, and publish complex topics as interactive process simulations, with active-recall questions and challenges for deeper learning.',
    'Laurentiu Raducu',
    'https://www.google.com/s2/favicons?domain=laurentiugabriel.github.io&sz=128',
    'How to Research',
    array['AI-Assisted Learning', 'Interactive Learning', 'Knowledge Visualization', 'Coding Agents', 'Simulation-Based Learning'],
    '6 min read',
    '2026-08-09',
    'Laurentiu Raducu',
    'https://laurentiugabriel.github.io/blog/articles/how-i-use-llms-to-learn/',
    'assets/img/covers/real/how-i-use-llms-to-learn.png',
    'How I use LLMs to learn complex topics article cover',
    'cover',
    'published',
    false
  )
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;

commit;
