-- Add six recent frontier model-release and research blogs to Supabase public.blogs:
-- GPT-6 Astra, Research acceleration (OpenAI), Atlas (World Labs), Solaris (Runway),
-- Gemini 3.8 Flash, and Claude Fable 5.1 / Mythos 5.1.
insert into public.blogs (id, title, excerpt, author, author_avatar, category, tags, read_time, publish_date, source_name, url, cover_image, cover_alt, cover_fit, status, featured)
values
('openai-gpt-6-astra', 'Introducing GPT-6 Astra', 'OpenAI releases GPT-6 Astra, its next-generation flagship model positioned as a generational leap with state-of-the-art performance across computer use, web browsing, software engineering, cybersecurity, and scientific research, alongside a dramatic jump on the ARC-AGI-3 benchmark.', 'OpenAI', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'Foundation Model', array['GPT-6 Astra','Frontier Model','AGI','Model Release','Reasoning'], '8 min read', '2026-09-03', 'OpenAI', 'https://openai.com/index/gpt-6-astra/', 'assets/img/covers/real/gpt-6.png', 'GPT-6 Astra article cover', 'cover', 'published', false),
('openai-research-acceleration-view-inside', 'Research acceleration: The view inside OpenAI', 'OpenAI discloses internal data on recursive self-improvement, showing how AI agents increasingly automate the research loop from idea generation to experiment execution, and announces that its automated research intern milestone has been reached.', 'OpenAI', 'https://www.google.com/s2/favicons?domain=openai.com&sz=128', 'AI Agents', array['Research Acceleration','Recursive Self-Improvement','AI Agents','Automated Research'], '12 min read', '2026-09-06', 'OpenAI', 'https://openai.com/index/research-acceleration-view-inside-openai/', 'assets/img/covers/real/research-acceleration-view-inside-openai.png', 'Research acceleration: The view inside OpenAI article cover', 'cover', 'published', false),
('world-labs-atlas-world-model', 'Introducing Atlas, Our Omni World Model for Spatial Intelligence', 'World Labs introduces Atlas, an omni world model pretrained natively on text, image, video, and 3D data with a multimodal autoregressive diffusion Transformer that fuses inputs into a unified spatial context, enabling camera-controlled generation, spatial reconstruction, spatiotemporal simulation, and image generation.', 'World Labs', 'https://www.google.com/s2/favicons?domain=worldlabs.ai&sz=128', 'World Model', array['World Model','Spatial Intelligence','3D Reconstruction','Camera Control','Diffusion Transformer'], '12 min read', '2026-09-01', 'World Labs', 'https://www.worldlabs.ai/blog/atlas', 'assets/img/covers/real/worldlabs-atlas.jpg', 'Atlas world model article cover', 'cover', 'published', false),
('runway-solaris-interface-world-model', 'Introducing Solaris', 'Runway introduces Solaris, the first model in its Interface World Models series, which renders interfaces frame by frame in response to clicks, drags, and natural-language commands; built on Gen-4.5, it separates reasoning from real-time rendering and treats applications as living, interactive environments.', 'Runway', 'https://www.google.com/s2/favicons?domain=runway.com&sz=128', 'World Model', array['Solaris','Interface World Models','Real-time Generation','Gen-4.5','Video Generation'], '10 min read', '2026-08-31', 'Runway', 'https://runway.com/news/research/introducing-solaris', 'assets/img/covers/real/runway_solaris.png', 'Runway Solaris article cover', 'cover', 'published', false),
('google-gemini-3-8-flash-cyber', 'Introducing Gemini 3.8 Flash and 3.8 Flash Cyber', 'Google introduces Gemini 3.8 Flash, its strongest reasoning and coding model, alongside 3.8 Flash Cyber, a cybersecurity-defense variant with frontier vulnerability discovery and auto-patching, both with strengthened prompt-injection and safety defenses.', 'Tulsee Doshi and Raluca Ada Popa', 'https://www.google.com/s2/favicons?domain=blog.google&sz=128', 'Foundation Model', array['Gemini 3.8 Flash','Cybersecurity','Reasoning','Coding','Model Release'], '8 min read', '2026-09-02', 'Google Blog', 'https://blog.google/innovation-and-ai/models-and-research/gemini-models/3-8-flash-and-3-8-flash-cyber/', 'assets/img/covers/real/gemini-3.8-flash.png', 'Gemini 3.8 Flash article cover', 'cover', 'published', false),
('anthropic-claude-fable-mythos-5-1', 'Introducing Claude Fable 5.1 and Mythos 5.1', 'Anthropic releases Claude Fable 5.1 and Mythos 5.1, two configurations of the same base model with different safeguard levels: Fable 5.1 for general use and Mythos 5.1 for trusted access in cybersecurity and life sciences, with gains across coding, knowledge work, and long-horizon tasks.', 'Anthropic', 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128', 'Foundation Model', array['Claude Fable 5.1','Claude Mythos 5.1','Coding','Model Release','AI Safety'], '8 min read', '2026-09-01', 'Anthropic', 'https://www.anthropic.com/claude-fable-and-mythos-5-1', 'assets/img/covers/real/claude-fable-5.1.png', 'Claude Fable 5.1 and Mythos 5.1 article cover', 'cover', 'published', false)
on conflict (id) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  author = excluded.author,
  author_avatar = excluded.author_avatar,
  category = excluded.category,
  tags = excluded.tags,
  read_time = excluded.read_time,
  publish_date = excluded.publish_date,
  source_name = excluded.source_name,
  url = excluded.url,
  cover_image = excluded.cover_image,
  cover_alt = excluded.cover_alt,
  cover_fit = excluded.cover_fit,
  status = excluded.status,
  featured = excluded.featured;
